baseurl = "/"
languageCode = "en-us"
title = "Nick Criswell"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
	weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ncriswell"
	weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/nrcriswell"
	weight = 4
[[menu.main]]
    name = "Home"
    url = "/"
	weight = 1

[taxonomies]
  tag = "tags"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.Logo]
    url = "Logo.png"
    width = 50
    height = 50
    alt = "Logo"

