---
title: 'TLST: TS 2017 Season Recap'
author: Nick Criswell
date: '2019-09-22'
slug: tlst-ts-2017-season-recap
categories:
  - fantasy
  - football
  - non-technical
  - R
tags: []
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(jsonlite)       # Pulling down JSON data
library(tidyverse)      # Tools for data analysis
library(glue)           # Sticking strings together
library(RColorBrewer)   # Color Pals
library(plotly)         # Interactive graphics
library(DT)             # JS DT libs
library(ggthemes)       # themes for ggplots
library(scales)         # better ggplot labels
```

```{r data gather, cache = TRUE}
source("C:/sleeper_fantasy/R/get_2017_data.R")
```

<script type="text/javascript">
  // When the document is fully rendered...
  $(document).ready(function() {
    // ...select all header elements...
    $('h1, h2, h3, h4, h5').each(function() {
      // ...and add an id to them corresponding to their 'titles'
      $(this).attr('id', $(this).html());
    });
  });
</script>

## Introduction


## Overall Season Performance


```{r}
weekly_owner_scores0 <- mu_unnest_view2 %>% 
  group_by(week, display_name, matchup_id) %>% 
  summarise(tot_points = round(sum(player_score, na.rm = TRUE), 2)) %>% 
  ungroup() %>% 
  mutate(week = as.numeric(week))

# Now do a sort of self join kind of deal to stick the points against. 

 weekly_owner_scores1 <- weekly_owner_scores0 %>% 
  left_join(weekly_owner_scores0, by = c("week", "matchup_id")) %>% 
  filter(display_name.x != display_name.y) %>% 
  mutate(Week = as.factor(week),
         display_name.x = as.factor(display_name.x)) %>% 
  select(Week, display_name.x, tot_points.x, tot_points.y) %>% 
  rename(`Owner` = display_name.x, 
         `Points For` = tot_points.x, 
         `Points Against` = tot_points.y) %>% 
  arrange(Week)

# get number of wins by owner
owner_wl0 <- weekly_owner_scores1 %>% 
  mutate(Win = `Points For` > `Points Against`,
         Loss = !Win) %>% 
  select(Owner, Win, Loss) %>% 
  group_by(Owner) %>% 
  summarise(Wins = sum(Win), 
            Losses = sum(Loss)) 

# lets also get the avearge points for and points against by owner
avg_owner_score <- weekly_owner_scores1 %>% 
  group_by(Owner) %>% 
  summarise(avg_points_for = round(mean(`Points For`), 0), 
            avg_points_against = round(mean(`Points Against`), 0))

# Stick these together and make a DT
owner_wl1 <- owner_wl0 %>% 
  left_join(avg_owner_score, by = c("Owner")) %>% 
  arrange(desc(Wins)) %>% 
  rename(`Avg Points For` = avg_points_for, 
         `Avg Points Against` = avg_points_against) 
  
datatable(owner_wl1,
          class = 'cell-border stripe',
          rownames = FALSE, 
          caption = "TLST 2017 NFL Season: Season Summary",
          filter = 'top',
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip', 
                         buttons = list('excel', "csv"),
                         pageLength = 14, autoWidth = TRUE))


```


```{r, fig.align='center', fig.width = 10, fig.height=10}

# get number of wins by owner
owner_wl0 <- weekly_owner_scores1 %>% 
  mutate(Win = `Points For` > `Points Against`,
         Loss = !Win) %>% 
  select(Owner, Win, Loss) %>% 
  group_by(Owner) %>% 
  summarise(Wins = sum(Win), 
            Losses = sum(Loss)) 

# lets also get the avearge points for and points against by owner
avg_owner_score <- weekly_owner_scores1 %>% 
  group_by(Owner) %>% 
  summarise(avg_points_for = round(mean(`Points For`), 0), 
            avg_points_against = round(mean(`Points Against`), 0))

# stick this onto the wl data
owner_wl_melt0 <- owner_wl1 %>% 
  mutate(`Owner For/Against` = paste0(Owner, ":", `Avg Points For`, "/", `Avg Points Against`)) %>% 
  select(Wins, Losses, `Owner For/Against`) %>% 
  gather(Outcome, value, -`Owner For/Against`)

ggplot(data = owner_wl_melt0, aes(x = `Owner For/Against`, y = value, fill = Outcome)) + 
  geom_col(position = "dodge") + 
  coord_flip() + 
  scale_x_discrete(name = "Owner: Avg Points For / Avg Points Against ") + 
  scale_y_continuous(breaks = 1:10, name = "Number of Wins or Losses") +
    scale_fill_brewer(palette = "Set1") + 
    ggtitle("TLST NFL Owner Win/Loss Record",
          subtitle = "y-axis label represents owner and average points for / points against record") + 
  labs(caption = "Data pulled through Sleeper API https://docs.sleeper.app/") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(),
        legend.title = element_blank()) 

```

## Overall Weekly Performance

```{r}

# we made something further up in the chain that we'll grab here

datatable(weekly_owner_scores1,
          class = 'cell-border stripe',
          rownames = FALSE, 
          caption = "TLST 2017 NFL Season: Weekly Scores",
          filter = 'top',
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip', 
                         buttons = list('excel', "csv"),
                          autoWidth = TRUE))

```



```{r, fig.align='center', fig.width= 12, fig.height=12}

# melth the data down so we can get points for/against as a column
weekly_owner_scores_melt0 <- weekly_owner_scores1 %>% 
  gather(Points, value, -Week, -Owner) %>% 
  group_by(Owner) 


ggplot(data = weekly_owner_scores_melt0, aes(x = Week, y = value, color = Points, group = Points)) +
  geom_line(size = 1.3) + 
  geom_hline(data = avg_owner_score, 
             aes(yintercept = avg_points_for), 
             colour = "#377EB8", linetype = "dashed", size = 1.15) + 
  geom_hline(data = avg_owner_score, 
             aes(yintercept = avg_points_against), 
             colour = "#E41A1C", linetype = "dashed", size = 1.15) + 
  facet_wrap(~Owner) + 
  scale_y_continuous("Point Total") + 
  scale_colour_brewer(palette = "Set1") + 
  facet_wrap(~Owner, scales = "free_x") + 
  ggtitle("TLST NFL Weekly Point Totals by Owner",
          subtitle = "Owner average indicated with dotted lines") + 
  labs(caption = "Data pulled through Sleeper API https://docs.sleeper.app/") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(),
        legend.title = element_blank()) 
  
  

```


```{r, fig.align='center', fig.width= 12, fig.height=12}

ggplot(data = weekly_owner_scores_melt0, aes(x = Owner, y = value, fill = Points)) +
  geom_boxplot() + 
  scale_y_continuous("Point Total") + 
  scale_fill_brewer(palette = "Set1") + 
  ggtitle("TLST NFL Weekly Point Totals Distribution by Owner") + 
  labs(caption = "Data pulled through Sleeper API https://docs.sleeper.app/") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(),
        legend.title = element_blank()) +
  coord_flip()


```


## Position Performance


```{r, fig.width = 8, fig.height = 8}
owner_position_view0 <- mu_unnest_view2 %>% 
  filter(!is.na(position)) %>% 
  group_by(display_name, position, week) %>% 
  summarise(tot_contribution = sum(player_score, na.rm = TRUE)) %>% 
  group_by(display_name, position) %>% 
  summarise(avg_contribution = mean(tot_contribution, na.rm = TRUE)) %>% 
  ungroup()

# overall averages
lg_position_view0 <- owner_position_view0 %>% 
  group_by(position) %>% 
  summarise(avg_contribution = mean(avg_contribution, na.rm = TRUE)) %>% 
  ungroup()

ggplot(data = owner_position_view0, 
       aes(x = display_name, y = avg_contribution)) +
  geom_hline(data = lg_position_view0, 
             aes(yintercept = avg_contribution, colour = position),
             show.legend = FALSE, size = 1.25) +
  geom_point(aes(colour = position), size = 5, alpha = 0.8) + 
  scale_colour_brewer(name = "Position", palette = "Set1") + 
  scale_y_continuous(name = "Average Weekly Position Contribution") + 
  scale_x_discrete(name = "") + 
  ggtitle("Average Weekly Contribution by Position and Owner", 
          subtitle = "Vertical lines represent league weekly average") + 
  labs(caption = "Data pulled through Sleeper API https://docs.sleeper.app/") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(),
        legend.title = element_blank()) + 
  coord_flip()
    
```



```{r, fig.height = 13, fig.width = 13}
week_position_view0 <- mu_unnest_view2 %>% 
  group_by(display_name, position, week) %>% 
  summarise(position_score = sum(player_score)) %>% 
  ungroup() 

ggplot(data = week_position_view0, 
       aes(x = as.numeric(week), 
           y = position_score, 
           fill = position, 
           label = position_score)) + 
  geom_col(colour = "black") + 
  facet_wrap(~display_name) +
  scale_x_continuous(breaks = 1:16, name = "Week") +
  scale_y_continuous(name = "Total Score") + 
  scale_fill_brewer(name = "Position", palette = "Set1") + 
  ggtitle("Weekly Contribution by Position and Owner") + 
  labs(caption = "Data pulled through Sleeper API https://docs.sleeper.app/") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(),
        legend.title = element_blank()) 


```


## Player Performance


```{r}

player_week_view0 <- mu_unnest_view2 %>% 
  filter(!is.na(player_score)) %>% 
  select(display_name, week, matchup_id, last_name, 
         first_name, position, player_score) %>% 
  mutate(Week = as.factor(as.numeric(week)),
         score = round(player_score, 2)) %>% 
  mutate_at(c("display_name", "matchup_id", "last_name", "first_name", "position"), as.factor) %>% 
  select(-week, -player_score) %>% 
  rename(Owner = display_name, 
         Matchup = matchup_id, 
         `Last Name` = last_name, 
         `First Name` = first_name, 
         Position = position, 
         Score = score) %>% 
  select(Week, everything())

datatable(player_week_view0,
          class = 'cell-border stripe',
          rownames = FALSE, 
          caption = "TLST 2017 NFL Season: Player Weekly Scores",
          filter = 'top',
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip', 
                         buttons = list('excel', "csv"),
                         pageLength = 14, autoWidth = TRUE))

```

